package converters

import (
	"fmt"

	"github.com/duynguyendang/manglekit/core"
	"github.com/google/mangle/ast"
)

// DocumentConverter implements the core.FactConverter interface for core.Doc objects.
// It translates a document's ID, content, and metadata into Datalog facts that
// can be used by the Mangle engine, typically in the post-processing stage.
type DocumentConverter struct{}

// NewDocumentConverter creates a new DocumentConverter.
func NewDocumentConverter() (core.FactConverter, error) {
	return &DocumentConverter{}, nil
}

// ToFacts converts a core.Doc object into a slice of Mangle facts.
// It generates the following facts:
//   - doc_id(DocID)
//   - doc_content(DocID, Text)
//   - doc_metadata(DocID, Key, Value) for each metadata entry.
//
// input must be of type core.Doc.
// It returns a slice of ast.Atom or an error if the input is not a core.Doc.
func (c *DocumentConverter) ToFacts(input any) ([]ast.Atom, error) {
	doc, ok := input.(core.Doc)
	if !ok {
		return nil, fmt.Errorf("expected core.Doc, got %T", input)
	}

	var facts []ast.Atom
	facts = append(facts, ast.NewAtom("doc_id", ast.String(doc.ID)))
	facts = append(facts, ast.NewAtom("doc_content", ast.String(doc.ID), ast.String(doc.Text)))
	// Provide a doc_text alias to simplify rules that expect a single-argument predicate.
	facts = append(facts, ast.NewAtom("doc_text", ast.String(doc.Text)))
	for key, value := range doc.Meta {
		switch v := value.(type) {
		case string:
			facts = append(facts, ast.NewAtom("doc_metadata", ast.String(doc.ID), ast.String(key), ast.String(v)))
		case []any:
			for _, item := range v {
				itemStr, ok := item.(string)
				if ok {
					facts = append(facts, ast.NewAtom("doc_metadata", ast.String(doc.ID), ast.String(key), ast.String(itemStr)))
				}
			}
		}
	}
	return facts, nil
}

// Predicates returns the Mangle Datalog predicate declarations for the facts
// generated by this converter. This is required for the Mangle engine to
// validate the program.
func (c *DocumentConverter) Predicates() []ast.PredicateSym {
	return []ast.PredicateSym{
		{Symbol: "doc_id", Arity: 1},
		{Symbol: "doc_content", Arity: 2},
		{Symbol: "doc_text", Arity: 1},
		{Symbol: "doc_metadata", Arity: 3},
	}
}
