package llm

// Request encapsulates the input for a large language model (LLM) completion
// request. It provides a structured way to define the prompt, context, and
// other parameters for the generation task.
type Request struct {
	// Prompt is the template or instruction for the LLM. It may contain placeholders
	// that are populated using the Data field.
	Prompt string
	// Context is a slice of textual passages (e.g., from a retriever) that are
	// intended to ground the LLM's response in factual evidence.
	Context []string
	// MaxTokens is the maximum number of tokens to generate in the response.
	MaxTokens int
	// Data is a map of arbitrary key-value data that can be used to populate
	// a dynamic prompt template before it is sent to the LLM.
	Data map[string]any
}

// Response represents the output from an LLM completion. It contains the
// generated text and metadata about the generation process.
type Response struct {
	// Text is the main text content generated by the language model.
	Text string
	// Usage is a map containing token usage statistics for the request,
	// typically including prompt tokens, completion tokens, and total tokens,
	// e.g., {"prompt_tokens": 100, "completion_tokens": 250}.
	Usage map[string]int
}

// Client defines the standard interface for a large language model client.
// Implementations of this interface provide a consistent way to interact with
// different LLM providers (e.g., OpenAI, Google Gemini).
type Client interface {
	// Complete takes a structured Request, sends it to the language model, and
	// returns a structured Response.
	//
	// req is the LLM completion request, containing the prompt, context, and
	// other generation parameters.
	// It returns a Response containing the generated text and usage data,
	// or an error if the API call or processing fails.
	Complete(req Request) (Response, error)
}
