package pipeline

import (
	"context"
	"time"

	"github.com/duynguyendang/manglekit/core"
	"github.com/duynguyendang/manglekit/rerank"
)

// PipelineContext is a typed, mutable data carrier that flows through the stages
// of the orchestration pipeline. It holds all inputs, intermediate artifacts,
// and final results, eliminating the need for "magic string" maps.
type PipelineContext struct {
	// Ctx is the request-scoped context that must be propagated through all stages.
	Ctx context.Context

	// === Inputs ===
	// Query is the original user query. It may be mutated by the PreRulesStage.
	Query core.Query
	// History is the conversation history for the current session.
	History *core.ConversationHistory
	// SessionID is the unique identifier for the conversation session.
	SessionID string

	// === Artifacts ===
	// OriginalDocs are the documents returned by the initial retrieval stage.
	OriginalDocs []core.Doc
	// RerankedDocs are the scored and sorted documents from the reranking stage.
	RerankedDocs []rerank.ScoredDoc
	// FinalDocs are the documents selected to be used for the LLM context,
	// typically after reranking or fallback logic has been applied.
	FinalDocs []core.Doc
	// Citations are the generated citations based on FinalDocs.
	Citations []core.Citation
	// Response is the final textual answer generated by the LLM.
	Response string
	// Answer is the final, assembled answer object.
	Answer core.Answer

	// === Metrics ===
	// StartTime is the timestamp when the pipeline execution began.
	StartTime time.Time
	// RetrieveMS is the latency of the retrieval stage in milliseconds.
	RetrieveMS float64
	// RerankMS is the latency of the reranking stage in milliseconds.
	RerankMS float64
	// LLMMS is the latency of the LLM stage in milliseconds.
	LLMMS float64
	// BestScore is the highest score from the reranker, used for fallback logic.
	BestScore float64

	// Err is used to capture an error from a stage and signal the runner to stop.
	Err error
}

// Result is the final, immutable, and typed output of a successful pipeline execution.
// It is constructed from the PipelineContext at the end of the run.
type Result struct {
	// Answer is the final answer, including the response text and citations.
	Answer core.Answer
	// RetrieveMS is the latency of the retrieval stage in milliseconds.
	RetrieveMS float64
	// RerankMS is the latency of the reranking stage in milliseconds.
	RerankMS float64
	// LLMMS is the latency of the LLM stage in milliseconds.
	LLMMS float64
	// BestScore is the highest score from the reranker.
	BestScore float64
}
