package rulegenerator

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/google/mangle/analysis"
	"github.com/google/mangle/ast"
	"github.com/google/mangle/engine"
	"github.com/google/mangle/factstore"
	"github.com/google/mangle/parse"
)

// Evaluator provides rule evaluation capabilities for generated Datalog rules.
// It encapsulates all Mangle engine internals, providing a clean API for
// executing rules against Go structs.
type Evaluator struct {
	rule     string
	clause   ast.Clause
	ruleHead string // e.g., "deny", "allow", "route"
}

// NewEvaluator creates an Evaluator from a validated Datalog rule string.
// The rule must have been generated by Generator.GenerateRule to ensure validity.
func NewEvaluator(rule string) (*Evaluator, error) {
	if rule == "" {
		return nil, fmt.Errorf("rule cannot be empty")
	}

	clause, err := parse.Clause(rule)
	if err != nil {
		return nil, fmt.Errorf("failed to parse rule: %w", err)
	}

	// Extract the rule head predicate name (e.g., "deny" from "deny(Req)")
	ruleHead := ""
	if clause.Head.Predicate.Symbol != "" {
		ruleHead = clause.Head.Predicate.Symbol
	}

	return &Evaluator{
		rule:     rule,
		clause:   clause,
		ruleHead: ruleHead,
	}, nil
}

// EvaluateResult contains the result of evaluating a rule against an entity.
type EvaluateResult struct {
	// Matched indicates whether the rule's head predicate was derived for this entity.
	Matched bool
	// EntityID is the identifier used for this evaluation.
	EntityID string
	// RuleHead is the predicate that was checked (e.g., "deny", "allow").
	RuleHead string
}

// Evaluate runs the Datalog rule against the provided struct and returns
// whether the rule's head predicate was derived.
//
// entityID: A unique identifier for this entity (used in facts like amount("entityID", 100))
// entity: A struct with `mangle` tags defining the predicates
func (e *Evaluator) Evaluate(entityID string, entity any) (EvaluateResult, error) {
	result := EvaluateResult{
		EntityID: entityID,
		RuleHead: e.ruleHead,
	}

	// Convert entity to Mangle facts
	facts, err := structToFacts(entityID, entity)
	if err != nil {
		return result, fmt.Errorf("failed to convert entity to facts: %w", err)
	}

	// Set up the fact store and add initial facts
	store := factstore.NewSimpleInMemoryStore()
	knownPredicates := make(map[ast.PredicateSym]ast.Decl)

	for _, atom := range facts {
		store.Add(atom)
		if _, ok := knownPredicates[atom.Predicate]; !ok {
			knownPredicates[atom.Predicate] = ast.NewSyntheticDeclFromSym(atom.Predicate)
		}
	}

	// Analyze the program
	program := []ast.Clause{e.clause}
	programInfo, err := analysis.AnalyzeOneUnit(parse.SourceUnit{Clauses: program}, knownPredicates)
	if err != nil {
		return result, fmt.Errorf("failed to analyze program: %w", err)
	}

	// Evaluate - this materializes all consequences into the store
	if err := engine.EvalProgram(programInfo, store); err != nil {
		return result, fmt.Errorf("failed to evaluate program: %w", err)
	}

	// Check if the rule head was derived for this entity
	queryStr := fmt.Sprintf(`%s("%s")`, e.ruleHead, entityID)
	queryAtom, err := parse.Atom(queryStr)
	if err != nil {
		return result, fmt.Errorf("failed to parse query: %w", err)
	}

	result.Matched = store.Contains(queryAtom)
	return result, nil
}

// structToFacts converts a Go struct to Mangle atoms in the format:
// predicate("entityID", value)
//
// It uses the `mangle` struct tag to determine predicate names.
// If no tag is present, the lowercase field name is used.
func structToFacts(entityID string, entity any) ([]ast.Atom, error) {
	val := reflect.ValueOf(entity)
	if val.Kind() == reflect.Ptr {
		if val.IsNil() {
			return nil, fmt.Errorf("entity cannot be nil")
		}
		val = val.Elem()
	}
	if val.Kind() != reflect.Struct {
		return nil, fmt.Errorf("entity must be a struct, got %v", val.Kind())
	}

	typ := val.Type()
	var atoms []ast.Atom

	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		fieldVal := val.Field(i)

		// Skip unexported fields
		if !field.IsExported() {
			continue
		}

		// Get predicate name from tag or field name
		tag := field.Tag.Get("mangle")
		if tag == "-" {
			continue // Skip fields marked with mangle:"-"
		}
		if tag == "" {
			tag = strings.ToLower(field.Name)
		}

		// Create the atom based on field type
		var atom ast.Atom
		switch fieldVal.Kind() {
		case reflect.Int, reflect.Int64, reflect.Int32, reflect.Int16, reflect.Int8:
			atom = ast.NewAtom(tag, ast.String(entityID), ast.Number(fieldVal.Int()))
		case reflect.Uint, reflect.Uint64, reflect.Uint32, reflect.Uint16, reflect.Uint8:
			atom = ast.NewAtom(tag, ast.String(entityID), ast.Number(int64(fieldVal.Uint())))
		case reflect.Float32, reflect.Float64:
			// Mangle doesn't have float, convert to string
			atom = ast.NewAtom(tag, ast.String(entityID), ast.String(fmt.Sprintf("%f", fieldVal.Float())))
		case reflect.String:
			atom = ast.NewAtom(tag, ast.String(entityID), ast.String(fieldVal.String()))
		case reflect.Bool:
			boolStr := "false"
			if fieldVal.Bool() {
				boolStr = "true"
			}
			atom = ast.NewAtom(tag, ast.String(entityID), ast.String(boolStr))
		default:
			// Skip unsupported types
			continue
		}
		atoms = append(atoms, atom)
	}

	if len(atoms) == 0 {
		return nil, fmt.Errorf("no valid facts could be extracted from entity")
	}

	return atoms, nil
}
