package core

import (
	"context"
)

// LLMRequest encapsulates the input for a large language model (LLM) completion
// request. It provides a structured way to define the prompt, context, and
// other parameters for the generation task.
type LLMRequest struct {
	// Prompt is the template or instruction for the LLM. It may contain placeholders
	// that are populated using the Data field.
	Prompt string
	// Context is a slice of textual passages (e.g., from a retriever) that are
	// intended to ground the LLM's response in factual evidence.
	Context []string
	// MaxTokens is the maximum number of tokens to generate in the response.
	MaxTokens int
	// Data is a map of arbitrary key-value data that can be used to populate
	// a dynamic prompt template before it is sent to the LLM.
	Data map[string]any
}

// LLMResponse represents the output from an LLM completion. It contains the
// generated text and metadata about the generation process.
type LLMResponse struct {
	// Text is the main text content generated by the language model.
	Text string
	// Usage is a map containing token usage statistics for the request,
	// typically including prompt tokens, completion tokens, and total tokens,
	// e.g., {"prompt_tokens": 100, "completion_tokens": 250}.
	Usage map[string]int
}

// LLMClient defines the standard interface for a large language model client.
// Implementations of this interface provide a consistent way to interact with
// different LLM providers (e.g., OpenAI, Google Gemini).
type LLMClient interface {
	// Complete takes a structured Request, sends it to the language model, and
	// returns a structured Response.
	//
	// ctx is the context for the API call.
	// req is the LLM completion request, containing the prompt, context, and
	// other generation parameters.
	// It returns a Response containing the generated text and usage data,
	// or an error if the API call or processing fails.
	Complete(ctx context.Context, req LLMRequest) (LLMResponse, error)
}

// RerankRequest encapsulates the input for a reranking operation. It contains the
// query and the initial set of documents to be re-ordered.
type RerankRequest struct {
	// Query is the original user query string, which is used to assess the
	// relevance of each document.
	Query string
	// Docs is the slice of documents retrieved from the initial retrieval stage
	// that need to be reranked.
	Docs []Doc
	// TopK is the desired number of documents to return after reranking. The
	// implementation should return at most this many of the top-scoring documents.
	TopK int
}

// ScoredDoc represents a document that has been assigned a new relevance score
// by a Reranker. This struct is used to hold the output of the reranking process.
type ScoredDoc struct {
	// Doc is the original document that was scored.
	Doc Doc
	// Score is the new relevance score assigned by the reranker. A higher score
	// is expected to indicate greater relevance to the query.
	Score float64
}

// Reranker defines the standard interface for components that re-score and
// re-order a list of documents based on their semantic relevance to a query.
// Rerankers are typically used after an initial, broader retrieval phase to
// refine the set of documents before they are passed to a language model.
type Reranker interface {
	// Rerank takes a Request, computes a new relevance score for each document
	// with respect to the query, and returns a new list of ScoredDoc, sorted
	// in descending order of relevance (highest score first).
	//
	// ctx is the context for the API call.
	// req is the reranking request containing the query and the initial list of documents.
	// It returns a sorted slice of ScoredDoc or an error if the reranking
	// operation fails.
	Rerank(ctx context.Context, req RerankRequest) ([]ScoredDoc, error)
}

// RetrieveRequest encapsulates a query to a retriever. It packages the query string,
// the desired number of results, and any additional metadata needed for the operation.
type RetrieveRequest struct {
	// Query is the textual query string to be used for retrieval. This could be
	// a natural language question or a set of keywords.
	Query string
	// TopK is the maximum number of documents to return.
	TopK int
	// Meta is a map for arbitrary metadata to be used by the retriever. This is
	// a flexible mechanism for passing contextual information, such as filters
	// generated by pre-retrieval rules, user identity, or other session data.
	Meta map[string]any
}

// RetrieveResult holds the documents and associated metadata returned by a retriever.
type RetrieveResult struct {
	// Docs is a slice of the documents that the retriever found to be relevant
	// to the query.
	Docs []Doc
	// Meta is a map for arbitrary metadata returned by the retriever. This can
	// include information like retrieval scores, timing data, or debugging info.
	Meta map[string]any
}

// Retriever is the core interface for components that can fetch documents
// based on a query. Implementations can range from simple keyword search to
// dense vector retrieval or complex hybrid methods.
type Retriever interface {
	// Retrieve takes a Request and returns a Result containing the most
	// relevant documents found by the implementation.
	//
	// ctx is the context for the API call.
	// req is the retrieval request, containing the query and other parameters.
	// It returns a Result containing the retrieved documents or an error if
	// the retrieval process fails.
	Retrieve(ctx context.Context, req RetrieveRequest) (RetrieveResult, error)
}

// ReasonerRequest encapsulates the input for a reasoner.
type ReasonerRequest struct {
	// Input is a map of arbitrary key-value data that can be used by the reasoner.
	Input map[string]any
}

// ReasonerResponse represents the output from a reasoner.
type ReasonerResponse struct {
	// Output is a map of arbitrary key-value data that is the result of the reasoning process.
	Output map[string]any
}

// Reasoner defines the standard interface for a symbolic reasoner.
// It is responsible for executing a set of rules or a logic program
// against a given input to produce a structured output.
type Reasoner interface {
	// Execute takes a structured Request, sends it to the reasoner, and
	// returns a structured Response.
	//
	// ctx is the context for the operation.
	// req is the reasoner request, containing the input data.
	// It returns a Response containing the output data,
	// or an error if the execution fails.
	Execute(ctx context.Context, req ReasonerRequest) (ReasonerResponse, error)
}

// Plan represents a structured sequence of steps to achieve a goal. It is the
// output of a Planner component. The plan consists of a series of steps, where
// each step defines a specific action (tool) to be executed with a given set of
// parameters.
type Plan struct {
	// Steps is a list of sequential actions to be taken to fulfill the user's request.
	Steps []Step `json:"steps"`
}

// Step is a single action within a Plan. It specifies the tool to be used, the
// parameters to be passed to it, and a descriptive reason for why this step is
// being taken.
type Step struct {
	// Tool is the name of the tool to be executed for this step. This name must
	// correspond to a registered Tool in the Manglekit framework.
	Tool string `json:"tool"`
	// Params is a map of key-value pairs that will be passed as parameters to the
	// specified tool. The structure of this map must match what the target tool expects.
	Params map[string]any `json:"params,omitempty"`
	// Reason is a natural language explanation of the purpose of this step within
	// the overall plan. This is useful for debugging, logging, and transparency.
	Reason string `json:"reason,omitempty"`
}

// Planner is the interface for components that can generate a multi-step plan
// to achieve a user's goal. Planners are a key part of the neuro-symbolic
// architecture, enabling the system to reason about how to combine different
// tools to solve complex problems.
type Planner interface {
	// Plan takes a user's goal (expressed as a query) and generates a structured
	// Plan.
	//
	// ctx is the context for the operation.
	// q is the user's query or goal.
	// It returns a Plan struct detailing the steps to be executed, or an error
	// if a plan cannot be formulated.
	Plan(ctx context.Context, q Query) (Plan, error)
}

// Action defines a generic interface for an executable unit of work.
// It generalizes components like Retrievers, Tools, and other processors.
type Action interface {
	// Execute performs the action with the given input and returns an output.
	//
	// ctx is the context for the operation.
	// input is the input data for the action.
	// It returns the output data or an error if the execution fails.
	Execute(ctx context.Context, input any) (any, error)
}

// Updatable defines the interface for retrievers that support runtime
// modification of their document index. This is useful for systems where the
// knowledge base can change without restarting the application. A component that
// implements this interface must also embed the base Retriever interface.
type Updatable interface {
	Retriever
	// Upsert adds new documents or updates existing ones in the index. If a
	// document with the same ID already exists in the index, it should be
	// replaced with the new version.
	//
	// docs is a slice of documents to add or update in the retriever's index.
	// It returns an error if the upsert operation fails.
	Upsert(ctx context.Context, docs []Doc) error
	// Replace clears the entire existing index and replaces it with a new set
	// of documents. This is a destructive operation useful for completely
	// refreshing the retriever's knowledge base.
	//
	// docs is the new, complete slice of documents to populate the index with.
	// It returns an error if the replacement operation fails.
	Replace(ctx context.Context, docs []Doc) error
}
