package converters

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/duynguyendang/manglekit/core"
	"github.com/google/mangle/ast"
)

var (
	versionRegexp = regexp.MustCompile(`v[0-9]+\.[0-9]+`)
)

// QueryConverter implements the core.FactConverter interface for core.Query objects.
// It analyzes the query text to extract structured information like version
// numbers and tokens, making them available as facts for Mangle rules.
type QueryConverter struct{}

// NewQueryConverter creates a new QueryConverter.
func NewQueryConverter() (core.FactConverter, error) {
	return &QueryConverter{}, nil
}

// ToFacts converts a core.Query object into a slice of Mangle facts.
// It performs normalization and tokenization on the query text.
// It generates the following facts:
//   - query_version(Version) if a version string is found.
//   - query_token(Token) for each unique token in the query.
//   - raw_query(Text) for the original, unmodified query text.
//   - normalized_query(Text) for the lowercased, trimmed query text.
//
// input must be of type core.Query.
// It returns a slice of ast.Atom or an error if the input is not a core.Query.
func (c *QueryConverter) ToFacts(input any) ([]ast.Atom, error) {
	query, ok := input.(core.Query)
	if !ok {
		return nil, fmt.Errorf("expected core.Query, got %T", input)
	}

	var facts []ast.Atom
	normalized := strings.ToLower(strings.TrimSpace(query.Text))

	if match := versionRegexp.FindString(normalized); match != "" {
		facts = append(facts, ast.NewAtom("query_version", ast.String(match)))
	}
	tokens := tokenize(normalized)
	for _, token := range tokens {
		facts = append(facts, ast.NewAtom("query_token", ast.String(token)))
	}
	facts = append(facts, ast.NewAtom("raw_query", ast.String(query.Text)))
	facts = append(facts, ast.NewAtom("normalized_query", ast.String(normalized)))
	return facts, nil
}

// Predicates returns the Mangle Datalog predicate declarations for the facts
// generated by this converter.
func (c *QueryConverter) Predicates() []ast.PredicateSym {
	return []ast.PredicateSym{
		{Symbol: "query_version", Arity: 1},
		{Symbol: "query_token", Arity: 1},
		{Symbol: "raw_query", Arity: 1},
		{Symbol: "normalized_query", Arity: 1},
	}
}

func tokenize(query string) []string {
	if query == "" {
		return nil
	}
	fields := strings.FieldsFunc(query, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9')
	})
	seen := make(map[string]struct{})
	result := make([]string, 0, len(fields))
	for _, token := range fields {
		if token == "" {
			continue
		}
		if _, ok := seen[token]; ok {
			continue
		}
		seen[token] = struct{}{}
		result = append(result, token)
	}
	return result
}