package converters

import (
	"fmt"
	"strings"

	"github.com/duynguyendang/manglekit/core"
	"github.com/google/mangle/ast"
)

// UserContextConverter implements the core.FactConverter interface for extracting
// user-related context from a core.Query object's metadata.
type UserContextConverter struct{}

// NewUserContextConverter creates a new UserContextConverter.
func NewUserContextConverter() (core.FactConverter, error) {
	return &UserContextConverter{}, nil
}

// ToFacts converts key-value pairs from a query's metadata into Mangle facts.
// It intelligently creates `ast.Name` constants for values wrapped in angle
// brackets (e.g., "<http://...>") and `ast.String` for all other values.
func (c *UserContextConverter) ToFacts(input any) ([]ast.Atom, error) {
	query, ok := input.(core.Query)
	if !ok {
		return nil, fmt.Errorf("expected core.Query, got %T", input)
	}

	if query.Meta == nil {
		return nil, nil
	}

	userCtx, ok := query.Meta["user_context"].(map[string]any)
	if !ok {
		return nil, nil // No user context to process.
	}

	var facts []ast.Atom
	for key, value := range userCtx {
		valueStr := fmt.Sprintf("%v", value)
		var valueTerm ast.BaseTerm

		// If the value is wrapped in angle brackets, treat it as an identifier (Name).
		if strings.HasPrefix(valueStr, "<") && strings.HasSuffix(valueStr, ">") {
			nameConst, err := iriToName(valueStr)
			if err != nil {
				// If conversion fails, fallback to a string for safety.
				valueTerm = ast.String(valueStr)
			} else {
				valueTerm = nameConst
			}
		} else {
			valueTerm = ast.String(valueStr)
		}
		facts = append(facts, ast.NewAtom("user_attribute", ast.String(key), valueTerm))
	}
	return facts, nil
}

// Predicates returns the Mangle Datalog predicate declarations for the facts
// generated by this converter.
func (c *UserContextConverter) Predicates() []ast.PredicateSym {
	return []ast.PredicateSym{
		{Symbol: "user_attribute", Arity: 2},
	}
}

// iriToName converts an IRI-like string (e.g., "<http://foo.com/bar>") into
// a Mangle Name constant (e.g., /foo.com/bar). It returns an error if the
// input is not a valid IRI-like string.
func iriToName(iriStr string) (ast.Constant, error) {
	if !strings.HasPrefix(iriStr, "<") || !strings.HasSuffix(iriStr, ">") {
		return ast.Constant{}, fmt.Errorf("not an IRI-like string: %s", iriStr)
	}
	// Trim the angle brackets.
	content := strings.TrimSuffix(strings.TrimPrefix(iriStr, "<"), ">")

	// Heuristically convert to a path-like structure for ast.Name.
	// e.g., "http://example.com/foo" -> "/example.com/foo"
	if parts := strings.SplitN(content, "://", 2); len(parts) > 1 {
		content = parts[1]
	}
	if !strings.HasPrefix(content, "/") {
		content = "/" + content
	}
	return ast.Name(content)
}
