package core

// Message represents a single message in a conversation flow.
// It is used for both input queries and system responses in chat-based interactions.
type Message struct {
	// Role indicates the sender of the message (e.g., "user", "assistant", "system").
	Role string `json:"role"`
	// Content is the textual body of the message.
	Content string `json:"content"`
}

// ConversationHistory represents a sequence of messages in a dialogue.
// It is often serialized and stored in state or metadata to maintain context.
type ConversationHistory struct {
	// Messages is the ordered list of messages in the conversation.
	Messages []Message `json:"messages"`
}

// Query represents a structured user request containing text and optional metadata.
type Query struct {
	// Text is the primary natural language query from the user.
	Text string `json:"text"`
	// Meta contains additional arbitrary data associated with the query.
	Meta map[string]any `json:"meta,omitempty"`
}

// Answer represents a structured system response containing text and optional metadata.
type Answer struct {
	// Text is the primary natural language response generated by the system.
	Text string `json:"text"`
	// Meta contains additional arbitrary data associated with the response.
	Meta map[string]any `json:"meta,omitempty"`
}
