package retrieve

import (
	"context"

	"github.com/duynguyendang/manglekit/core"
)

// Request encapsulates a query to a retriever. It packages the query string,
// the desired number of results, and any additional metadata needed for the operation.
type Request struct {
	// Query is the textual query string to be used for retrieval. This could be
	// a natural language question or a set of keywords.
	Query string
	// TopK is the maximum number of documents to return.
	TopK int
	// Meta is a map for arbitrary metadata to be used by the retriever. This is
	// a flexible mechanism for passing contextual information, such as filters
	// generated by pre-retrieval rules, user identity, or other session data.
	Meta map[string]any
}

// Result holds the documents and associated metadata returned by a retriever.
type Result struct {
	// Docs is a slice of the documents that the retriever found to be relevant
	// to the query.
	Docs []core.Doc
	// Meta is a map for arbitrary metadata returned by the retriever. This can
	// include information like retrieval scores, timing data, or debugging info.
	Meta map[string]any
}

// Retriever is the core interface for components that can fetch documents
// based on a query. Implementations can range from simple keyword search to
// dense vector retrieval or complex hybrid methods.
type Retriever interface {
	// Retrieve takes a Request and returns a Result containing the most
	// relevant documents found by the implementation.
	//
	// ctx is the context for the API call.
	// req is the retrieval request, containing the query and other parameters.
	// It returns a Result containing the retrieved documents or an error if
	// the retrieval process fails.
	Retrieve(ctx context.Context, req Request) (Result, error)
}

// Updatable defines the interface for retrievers that support runtime
// modification of their document index. This is useful for systems where the
// knowledge base can change without restarting the application. A component that
// implements this interface must also embed the base Retriever interface.
type Updatable interface {
	Retriever
	// Upsert adds new documents or updates existing ones in the index. If a
	// document with the same ID already exists in the index, it should be
	// replaced with the new version.
	//
	// docs is a slice of documents to add or update in the retriever's index.
	// It returns an error if the upsert operation fails.
	Upsert(docs []core.Doc) error
	// Replace clears the entire existing index and replaces it with a new set
	// of documents. This is a destructive operation useful for completely
	// refreshing the retriever's knowledge base.
	//
	// docs is the new, complete slice of documents to populate the index with.
	// It returns an error if the replacement operation fails.
	Replace(docs []core.Doc) error
}
